import argparse
import json
import random
import signal
import sys
import time
import uuid
from datetime import datetime, timezone

import paho.mqtt.client as mqtt


BROKER_HOST = "localhost"
BROKER_PORT = 1883
MQTT_TOPIC = "ev/sensors/battery_temperature"
PUBLISH_INTERVAL_SECONDS = 5
CLIENT_ID_PREFIX = "ev-simulator-battery-temp"


class BatteryTemperatureSensor:
    """Simple temperature drift model for an EV battery pack."""

    def __init__(self, start_celsius: float = 28.0) -> None:
        self.temperature_celsius = start_celsius

    def read(self) -> float:
        # Drift a little each cycle to simulate normal pack behavior.
        drift = random.uniform(-0.3, 0.5)
        self.temperature_celsius = max(18.0, min(52.0, self.temperature_celsius + drift))
        return round(self.temperature_celsius, 2)


def on_connect(client: mqtt.Client, userdata, flags, reason_code, properties=None) -> None:
    if reason_code == 0:
        print(f"Connected to MQTT broker at {BROKER_HOST}:{BROKER_PORT}")
    else:
        print(f"MQTT connection failed with code {reason_code}")


def build_payload(vehicle_id: str, temperature_celsius: float) -> str:
    payload = {
        "vehicle_id": vehicle_id,
        "sensor": "battery_temperature",
        "value_celsius": temperature_celsius,
        "timestamp_utc": datetime.now(timezone.utc).isoformat(),
    }
    return json.dumps(payload)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="EV battery temperature simulator")
    parser.add_argument(
        "--vehicle-id",
        type=str,
        default=f"EV-{uuid.uuid4().hex[:8].upper()}",
        help="Vehicle ID to use (default: autogenerated on startup)",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    vehicle_id = args.vehicle_id
    mqtt_client_id = f"{CLIENT_ID_PREFIX}-{uuid.uuid4().hex[:10]}"

    running = True
    sensor = BatteryTemperatureSensor()

    def shutdown_handler(signum, frame) -> None:
        nonlocal running
        print("\nStopping EV simulator...")
        running = False

    signal.signal(signal.SIGINT, shutdown_handler)
    signal.signal(signal.SIGTERM, shutdown_handler)

    print(f"Starting simulator for vehicle_id={vehicle_id}")

    client = mqtt.Client(client_id=mqtt_client_id, protocol=mqtt.MQTTv5)
    client.on_connect = on_connect
    client.connect(BROKER_HOST, BROKER_PORT, keepalive=60)
    client.loop_start()

    try:
        while running:
            temperature = sensor.read()
            payload = build_payload(vehicle_id, temperature)
            result = client.publish(MQTT_TOPIC, payload=payload, qos=1)

            if result.rc == mqtt.MQTT_ERR_SUCCESS:
                print(f"Published to {MQTT_TOPIC}: {payload}")
            else:
                print(f"Publish failed with code {result.rc}")

            time.sleep(PUBLISH_INTERVAL_SECONDS)
    finally:
        client.loop_stop()
        client.disconnect()
        print("Disconnected from MQTT broker")


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:
        print(f"Fatal error: {exc}")
        sys.exit(1)
